[package]
name = "cord-cli-test-utils"
description = "CLI testing utilities"
version = "0.9.3-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
substrate-rpc-client = { workspace = true }
sp-rpc = { workspace = true }
assert_cmd = { workspace = true }
nix = { workspace = true }
regex = { workspace = true }
tokio = { features = ["full"], workspace = true }
cord-node-cli = { workspace = true }
cord-primitives = { workspace = true }
sc-cli = { workspace = true }
sc-service = { workspace = true }
futures = { workspace = true }

[features]
try-runtime = ["cord-node-cli/try-runtime"]
