[package]
name = "cord-weave-node-cli"
description = "A weave node built with Substrate and Cumulus."
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
edition.workspace = true
publish = false
build = "build.rs"

[lints]
workspace = true

[[bin]]
name = "weave"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
clap = { features = ["derive"], workspace = true }
codec = { workspace = true, default-features = true }
color-print = { workspace = true }
futures = { workspace = true }
hex-literal = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
docify = { workspace = true }
cord-weave-asset-hub-runtime.workspace = true
cord-weave-asset-hub-runtime.default-features = true
cord-weave-coretime-runtime.workspace = true
cord-weave-coretime-runtime.default-features = true
jsonrpsee = { features = ["server"], workspace = true }
parachains-common.workspace = true
parachains-common.default-features = true
cord-weave-system-parachains-constants.workspace = true
frame-benchmarking.workspace = true
frame-benchmarking.default-features = true
frame-benchmarking-cli.workspace = true
frame-benchmarking-cli.default-features = true
sp-runtime.workspace = true
sp-io.workspace = true
sp-io.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-session.workspace = true
sp-session.default-features = true
frame-try-runtime = { optional = true, workspace = true, default-features = true }
sc-consensus.workspace = true
sc-consensus.default-features = true
sp-tracing.workspace = true
sp-tracing.default-features = true
frame-support.workspace = true
frame-support.default-features = true
sc-cli.workspace = true
sc-cli.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-service.workspace = true
sc-service.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-transaction-pool.workspace = true
sc-transaction-pool.default-features = true
sp-transaction-pool.workspace = true
sp-transaction-pool.default-features = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-sync.workspace = true
sc-network-sync.default-features = true
sc-basic-authorship.workspace = true
sc-basic-authorship.default-features = true
sp-timestamp.workspace = true
sp-timestamp.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-genesis-builder.workspace = true
sp-block-builder.workspace = true
sp-block-builder.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sp-version.workspace = true
sp-version.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
sp-offchain.workspace = true
sp-offchain.default-features = true
frame-system-rpc-runtime-api.workspace = true
frame-system-rpc-runtime-api.default-features = true
pallet-transaction-payment.workspace = true
pallet-transaction-payment.default-features = true
pallet-transaction-payment-rpc-runtime-api.workspace = true
pallet-transaction-payment-rpc-runtime-api.default-features = true
sp-std.workspace = true
sp-std.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-consensus-aura.workspace = true
sp-consensus-aura.default-features = true
sc-sysinfo.workspace = true
sc-sysinfo.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool-api.default-features = true
substrate-frame-rpc-system.workspace = true
substrate-frame-rpc-system.default-features = true
pallet-transaction-payment-rpc.workspace = true
pallet-transaction-payment-rpc.default-features = true
substrate-state-trie-migration-rpc.workspace = true
substrate-state-trie-migration-rpc.default-features = true
cord-loom-node-cli = { features = [
    "loom-native",
], workspace = true, default-features = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
cord-loom-service.workspace = true
cord-loom-service.default-features = true
xcm.workspace = true
xcm.default-features = true
cumulus-client-cli.workspace = true
cumulus-client-cli.default-features = true
cumulus-client-collator.workspace = true
cumulus-client-collator.default-features = true
cumulus-client-consensus-aura.workspace = true
cumulus-client-consensus-aura.default-features = true
cumulus-client-consensus-relay-chain.workspace = true
cumulus-client-consensus-relay-chain.default-features = true
cumulus-client-consensus-common.workspace = true
cumulus-client-consensus-common.default-features = true
cumulus-client-consensus-proposer.workspace = true
cumulus-client-consensus-proposer.default-features = true
cumulus-client-parachain-inherent.workspace = true
cumulus-client-parachain-inherent.default-features = true
cumulus-client-service.workspace = true
cumulus-client-service.default-features = true
cumulus-primitives-aura.workspace = true
cumulus-primitives-aura.default-features = true
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
cumulus-relay-chain-interface.workspace = true
cumulus-relay-chain-interface.default-features = true

[build-dependencies]
substrate-build-script-utils.workspace = true
substrate-build-script-utils.default-features = true

[dev-dependencies]
assert_cmd = { workspace = true }
nix = { features = ["signal"], workspace = true }
tempfile = { workspace = true }
tokio = { version = "1.32.0", features = ["macros", "parking_lot", "time"] }
wait-timeout = { workspace = true }

[features]
default = []
runtime-benchmarks = [
    "cord-weave-asset-hub-runtime/runtime-benchmarks",
    "cord-weave-coretime-runtime/runtime-benchmarks",
    "cumulus-primitives-core/runtime-benchmarks",
    "frame-benchmarking-cli/runtime-benchmarks",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "parachains-common/runtime-benchmarks",
    "cord-loom-node-cli/runtime-benchmarks",
    "polkadot-primitives/runtime-benchmarks",
    "cord-loom-service/runtime-benchmarks",
    "sc-service/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
try-runtime = [
    "cord-weave-asset-hub-runtime/try-runtime",
    "cord-weave-coretime-runtime/try-runtime",
    "frame-support/try-runtime",
    "frame-try-runtime/try-runtime",
    "pallet-transaction-payment/try-runtime",
    "cord-loom-node-cli/try-runtime",
    "cord-loom-service/try-runtime",
    "sp-runtime/try-runtime",
]
fast-runtime = []
