[package]
name = "cord-test-runtime"
version = "0.9.3-dev"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { features = ["serde"], workspace = true }
sp-consensus-aura = { features = ["serde"], workspace = true }
sp-consensus-babe = { features = ["serde"], workspace = true }
sp-genesis-builder = { workspace = true }
sp-block-builder = { workspace = true }
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-inherents = { workspace = true }
sp-keyring = { workspace = true }
sp-offchain = { workspace = true }
sp-core = { features = ["serde"], workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
frame-support = { workspace = true }
sp-version = { workspace = true }
sp-session = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { features = ["serde"], workspace = true }
pallet-babe = { workspace = true }
pallet-balances = { workspace = true }
frame-executive = { workspace = true }
frame-system = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
pallet-timestamp = { workspace = true }
sp-consensus-grandpa = { features = ["serde"], workspace = true }
sp-trie = { workspace = true }
sp-transaction-pool = { workspace = true }
trie-db = { workspace = true }
sc-service = { features = ["test-helpers"], workspace = true, optional = true }
sp-state-machine = { workspace = true }
sp-externalities = { workspace = true }
sp-crypto-hashing = { workspace = true }

array-bytes = { workspace = true, optional = true }     # 3rd party
log = { workspace = true }
serde_json = { features = ["alloc"], workspace = true }
hex-literal = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
sc-block-builder = { workspace = true }
sc-executor = { workspace = true }
sc-executor-common = { workspace = true }
sp-consensus = { workspace = true }
cord-test-runtime-client = { workspace = true }
sp-tracing = { workspace = true }
json-patch = { workspace = true }
serde = { features = ["alloc", "derive"], workspace = true }
serde_json = { features = ["alloc"], workspace = true }
sc-chain-spec = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]

std = [
	"array-bytes",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"log/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"sc-executor/std",
	"sc-service",
	"scale-info/std",
	"serde/std",
	"serde_json/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-babe/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-keyring/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-state-machine/std",
	"sp-tracing/std",
	"sp-transaction-pool/std",
	"sp-trie/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"trie-db/std",
	"futures/std",
	"sp-crypto-hashing/std",
	"sp-std/std"
]
# Special feature to disable logging
disable-logging = ["sp-api/disable-logging"]
