[package]
name = "cord-service-test"
version = "0.9.3-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-channel = { workspace = true }
array-bytes = { workspace = true }
fdlimit = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
codec = { workspace = true }
parking_lot = { workspace = true }
tempfile = { workspace = true }
tokio = { features = ["time"], workspace = true }
sc-block-builder = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { workspace = true }
sc-consensus = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-network-sync = { workspace = true }
sc-service = { features = ["test-helpers"], workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }
sp-storage = { workspace = true }
sp-tracing = { workspace = true }
sp-trie = { workspace = true }
sp-io = { workspace = true }
cord-test-runtime = { workspace = true }
cord-test-runtime-client = { workspace = true }
