[package]
name = "cord-test-client"
description = "Client testing utilities"
version = "0.9.3-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true }
async-trait = { workspace = true }
codec = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { features = ["test-helpers"], workspace = true }
sc-consensus = { workspace = true }
sc-executor = { workspace = true }
sc-offchain = { workspace = true }
sc-service = { features = ["test-helpers"], workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }
sp-keystore = { workspace = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }
tokio = { features = ["sync"], workspace = true }
