[package]
name = "cord-weave-asset-hub-primitives"
description = "Primitives of AssetHubWeave parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Local
cord-weave-system-parachains-constants = { workspace = true }

# Substrate Based Dependencies
frame-support = { workspace = true }
sp-std = { workspace = true }

# Polkadot
xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"cord-weave-system-parachains-constants/std",
	"sp-std/std",
	"xcm/std",
]
