[package]
name = "cord-braid-base-runtime-constants"
description = "Braid Base runtime constants."
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
smallvec = { workspace = true }
frame-support = { workspace = true }
cord-primitives = { workspace = true }
cord-braid-runtime-common = { workspace = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "cord-primitives/std",
    "cord-braid-runtime-common/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-weights/std",
]
