[package]
name = "cord-test-runtime-transaction-pool"
version = "0.9.3-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
cord-test-runtime-client = { workspace = true }
